spring:
  application:
    name: UI Automation Scheduler
  
  datasource:
    url: jdbc:h2:file:./data/automation
    driver-class-name: org.h2.Driver
    username: sa
    password: 
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
  
  h2:
    console:
      enabled: true
      path: /h2-console
  
  quartz:
    job-store-type: jdbc
    properties:
      org:
        quartz:
          scheduler:
            instanceName: AutomationScheduler
            instanceId: AUTO
          jobStore:
            driverDelegateClass: org.quartz.impl.jdbcjobstore.StdJDBCDelegate
            useProperties: false
            tablePrefix: QRTZ_
            isClustered: false
          threadPool:
            threadCount: 10

automation:
  screenshot:
    path: ./screenshots
  driver:
    headless: false
    timeout: 30

server:
  port: 8080

logging:
  level:
    com.automation: DEBUG
    org.springframework.web: INFO
    org.hibernate: WARN 