spring:
  application:
    name: UI Automation Scheduler

  datasource:
    url: jdbc:h2:file:./data/automation
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        globally_quoted_identifiers: true

  h2:
    console:
      enabled: true
      path: /h2-console

automation:
  screenshot:
    path: ./screenshots
  driver:
    headless: false
    timeout: 30

server:
  port: 8080

logging:
  level:
    com.automation: DEBUG
    org.springframework.web: INFO
    org.hibernate: WARN